org: lordfernan
service: api-sismos-scraper

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::974671687457:role/LabRole
  environment:
    SCRAPINGBEE_API_KEY: ${env:SCRAPINGBEE_API_KEY}

functions:
  scrape_sismos:
    handler: scrap_sismos.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /scrape/sismos
          method: get
          cors: true
          integration: lambda

resources:
  Resources:
    TablaSismosIGP:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaSismosIGP
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
